### ISSUE TITLE
Get from sourceforge not working

### ISSUE THREAD

**Issue by acotty** [DigitalMediaServer/NSIS-INetC-plugin#7]
Th following fails, but works in Firefox:
        inetc::get /weaksecurity /connecttimeout 30 /receivetimeout 120 https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/installer/mingw-w64-install.exe.download $2

Any ideas?

**Comment by acotty** [comment]
Looks like an abandoned project.

**Comment by Nadahar** [comment]
It's not abandoned as such, but it's not being actively developed. I don't know why the above doesn't work, but I can't say that the comparison to Firefox isn't very meaningful.

It can be caused by a lot of things outside our control though, sourceforge might not like the user-agent for example. The Windows API used in this plugin relies on IE internally, so I wouldn't be surprised if IE's user-agent it being used. IE isn't exactly widely supported these days, so sourceforge might reject the request based on that. It can also be that sourceforge does some fancy redirects that the plugin can't keep up with.

The only thing I can suggest is to drop `weaksecurity` as I think there currently is a bug with the flags used for that. It shouldn't be any problems with sourceforge's HTTPS certificates anyway. The `weaksecurity` option is meant for use with self-signed HTTPS certificates or for use with Windows XP which doesn't support TLS 1.2 and similar situations where "normal" HTTPS won't work.
